spring:
  datasource:
    url: jdbc:mysql://soboksobuk.chrp3bkonfze.ap-northeast-2.rds.amazonaws.com/sobuksobuk?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: true
    profiles:
      include: create
    main:
      allow-bean-definition-overriding: true
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 'abcde'



logging.level:
  org.hibernate.SQL: debug

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
