spring:
  datasource:
    url: jdbc:mysql://soboksobuk.chrp3bkonfze.ap-northeast-2.rds.amazonaws.com:13306/sobuksobuk?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    show-sql: true
    open-in-view: true
    profiles:
      include: create
    main:
      allow-bean-definition-overriding: true
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 'abcde'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging.level:
  org.hibernate.SQL: debug

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: mainproject.bucket
    stack:
      auto: false